### ISSUE TITLE
Is shadow support planned?

### ISSUE THREAD

**Issue by cheeztaco** [jiaozi158/UnityVolumetricCloudsURP#2]
Hey quick question, is shadow support planned?
IIRC in HDRP they generate a light cookie with the cloud data and apply it to the main light.

Also thank you for your work with porting this over to URP!

**Comment by jiaozi158** [comment]
Hi, I'll see what I can do about this when I have time.

I won't say it's planned because I haven't started trying to add it yet. Also, the Render Graph support should be done first so that I don't need to go back and adjust the code again.

**Comment by jiaozi158** [comment]
Hi, it's now supported!
