### ISSUE TITLE
Render clouds on the second overlay camera

### ISSUE THREAD

**Issue by Sidiusz** [jiaozi158/UnityVolumetricCloudsURP#6]
![image](https://github.com/user-attachments/assets/7f2008bd-170e-4adf-9fbc-4b6602335219)
![image](https://github.com/user-attachments/assets/51f07b42-0d0c-4c01-b64b-379f8bce2b33)

Hi. I am using two cameras for my needs, is it possible to disable cloud rendering on the second camera? 
 Sorry if this is a stupid question

**Comment by Sidiusz** [comment]
Yeah i'm dumbass, i just create second "URP-HighFidelity-Renderer" and choose it in the camera, sorry lol

**Comment by jiaozi158** [comment]
Hi, glad to hear that you found the solution!

Yes, you can switch to a renderer without the clouds renderer feature to disable volumetric clouds for a specific camera.

Another way is to use the camera's [volume mask](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@14.0/manual/camera-component-reference.html#Environment:~:text=the%20Render%20Pipeline.-,Volume%C2%A0Mask,-Use%20the%20drop) to define which URP volumes affect this camera.
